version: "3"
services:
  database:
    # Dockerfile이 있는 위치
    image: skjin20800/basicnginx:database1.0
    # 외부에 공개할 host명
    hostname: dbhost
    # 내부에서 개방할 포트 : 외부에서 접근할 포트
    ports:
      - "3306:3306"
    volumes:
      - todo-mysql-data:/var/lib/mysql
    networks:
      - test_net # 커스텀 네트워크 사용
  backend:
    hostname: backendhost
    image: skjin20800/basicnginx:nodejs2.0
    # build: ./backend
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - test_net # 커스텀 네트워크 사용
  frontend:
    hostname: frontendhost
    image: skjin20800/basicnginx:react2.3
    # build: ./frontend
    # volumes:
    #   - frontend-volume:/app/build
    depends_on:
      - backend
    ports:
      - "3000:3000"
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    networks:
      - test_net # 커스텀 네트워크 사용
  # nginx:
  #   # image: skjin20800/basicnginx:nginx2.0
  #   build: ./nginx
  #   hostname: nginxhost
  #   volumes:
  #     - frontend-volume:/app/front
  #   ports:
  #     - "80:80"
  #   networks:
  #     - test_net # 커스텀 네트워크 사용
  #   depends_on:
  #     - frontend

networks:
  test_net: # 내가 만든 커스텀 네트워크명
    driver: bridge # 커스템 네트워크 연결방식 bridge, Host방식등 4~5개 정도있는데 보통 bridge방식을 많이 사용한다.
    # external: true #외부접속 허용

volumes:
  todo-mysql-data:
  frontend-volume:
